[ci-cd] Update Ruby OCI image registry URI to ECR
AWS Amplify workers often fail due to Docker Hub's unauthenticated pull
rate limit:

```
BUILD_CONTAINER_UNABLE_TO_PULL_IMAGE: Unable to pull customer's container image.
CannotPullContainerError: Error response from daemon: toomanyrequests: You have reached your unauthenticated pull rate limit.
https://www.docker.com/increase-rate-limit
```

To alleviate this we target Amazon's ECR (Amazon Elastic Container
Registry) "Public Gallery" which mirrors the "docker/library/ruby"
Docker Official Images.

Local testing performed by removing the Docker Hub sourced OCI image
and re-running make tests outlined in #35. As the OCI image's SHA256
hash is identical the test results were the same.